server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    hostname: localhost
com:
  hegetomi:
    tokenlib:
      keypaths:
        private: /Users/Tamás/Downloads/keypair.pem
        public: /Users/Tamás/Downloads/public.pem